# Generated by Django 5.2 on 2025-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Title of the note.', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated.')),
            ],
        ),
    ]
